export type Viusagelike = "do" 
    | "get" 
    | "info" 
    | "getUserInfo" 
    | "navigate" 
    | "find" 
    | "sort" 
    | "install" 
    | "comment" 
    | "getHelp"
    | "wrap"
    | "wrapInvert"
    | "backdrop"
    | "error"
    | "success";